### ISSUE TITLE
Regular Linux ARM64 Desktop Builds (Rasberry Pi)

### ISSUE THREAD

**Issue by mzinner** [Alex313031/Thorium-SSE3#4]
Hi Thorium-Team,

thanks so much for working Thorium, it is the perfect Chromium-based browser! I am in the process of replacing all my Brave and Chromium installations on all systems with Thorium. Therefor the following request.

Would it be possible to add regular Linux ARM64 Desktop Builds to this repo?

This would allow me to run it on all my Raspberry Pi OS ARM64 as well as my VMs on my Apple M1 machines.

Thanks,
Mike

**Comment by Alex313031** [comment]
@mzinner For sure. I already made an ARM32 build for raspi 2 and 3 boards, but I'll for sure make you a ARM64 build. Keep in mind though that I am not a team, just a single 21 y.o. with a 4790K, and I am already bogged down building for linux, windows, and avx2, so arm32 and arm64 updates will come less fequently, but now that I know there is someone out there that wants them, I will make one soon.

**Comment by mzinner** [comment]
@Alex313031 wow, I didn't realize this is just you doing all the work! Would it help to sponsor a Raspberry Pi 4 for you for regular ARM64 Linux builds?  If so, do you have a Paypal account?

**Comment by Alex313031** [comment]
@mzinner What do you mean sponsor a raspi 4? If you mean donating a raspi 4 or money for a raspi 4, yes that would be helpful. I also would like a raspberry pi 4 anyways to test ChromiumOS builds on it. I make chromiumos builds with kernel 5.10, extra linux firmware, extra packages, codecs, and the compiler optimizations of Thorium but for the whole OS here > https://github.com/Alex313031/ChromiumOS.

Also, I am making your ARM64 build now.

**Comment by mzinner** [comment]
Yes, I meant to donate some money to you via PayPal so you could order a Raspberry Pi 4 and build/test Thorium on that.

**Comment by Alex313031** [comment]
@That would be awesome! I could build/test Thorium as well as ChromiumOS. That's very generous of you! I can build the ARM64 on my main build machine, but because it has to use translation units since its a different architecture, it would actually probably build faster on a Raspi 4 since it is native arm. I could also build it with NEON (armv8 vector extensions, kind of think of it as "AVX" but for arm) since NEON codegen isnt supported in clang x64 > arm64 cross compile yet.

Also, the arm64 build failed, but it was because I hadn't updated the arm.gni file since the arm32 build which was months ago. I will rebuild now.

Also, it's just incredibly generous and I thank you so much that you would be willing to give your own money like that. I had a paypal account, but when I tried to dispute an ebay purchase where a guy sent DDR3 sticks that didn't work, somehow it was *my* fault and they disabled my account. I'll make a new one.

**Comment by Alex313031** [comment]
@mzinner I updated the arm.gni in the main repo, and I also made an arm.gni in this repo that is specifically for the raspi 4 i.e. it has -march=armv8-a and -mtune=cortex-a72 since that is what the BCM2711 SoC on the Pi 4 and 400 uses.

**Comment by Alex313031** [comment]
@mzinner Here ya go, my fine sir. > https://github.com/Alex313031/Thorium-Special/releases/tag/M102.0.4972.0
And yeah, that or I found that a really fast MicroSD and then using the bootconfig.txt to overclock the SPI SDCard Bus from 50 to 100 mhz (along with the CPU and GPU of course lol) gives decent speed.

Also, my paypal is Alex313031@gmail.com

And, yeah I would verify that it works on raspbian and ubuntu 20.04 on the pi.

**Comment by mzinner** [comment]
Hi Alex,

I am getting an error when trying to send the money. "Your recipient can't accept payments right now". Please check which steps are yet missing to confirm the account. 

Best,
Mike

**Comment by Alex313031** [comment]
@mzinner It's because they disabled my account, see edit on above comment. I will have to make a new one, and maybe use my moms card since you can't reuse info from a previous account. Makes me mad. It legitimately was not my fault, and I still don't get how I "didn't abide by their guidelines".

**Comment by Alex313031** [comment]
@mzinner Oh and also, I used a fresh LLVM build and pointed the chromium toolchain to that instead of its internal prebuilt one, and the latest DOES support NEON. So I enabled it and that ARM64 can take advantage of the raspi's neon instruction set, which is nice.

**Comment by Alex313031** [comment]
@mzinner Making a new ARM64 build soon!

**Comment by mzinner** [comment]
Hi @Alex313031, that's great, already saw them! Did you find a solution regarding the PayPal account? My offer to donate some money to you still stands. I'll drop you an email on that topic, let's continue that discussion there.

Again, thanks for all your work on Thorium!

**Comment by Alex313031** [comment]
@mzinner Check out new website for thorium along with a new deb repo for auto updating on linux (amd64 for now, will add raspi builds later) > https://thorium.rocks/

**Comment by Alex313031** [comment]
@mzinner I finally got paypal working
Heres my paypal.me link > https://paypal.me/alex313031?country.x=US&locale.x=en_US

**Comment by mzinner** [comment]
@Alex313031 Great! Donation sent. A build for Windows on ARM would be very good to have. Looking forward to test it!

**Comment by Alex313031** [comment]
@mzinner Its about time to make a new raspi build. Last build was M103, and M105 was launched two days ago! Sorry I didn't make an M104 build for you. The windows on arm builds we are having trouble compiling, but we are cross compiling on linux. While you can apparently do this, it is not a supported use case, and @gz83 has been back and forth on the Chromium dev group, and I have been trying to help him with compiler errors. If all else fails, I will break down and try to make a native build on windows. And how would you test it? Do you have an ARM device running windows?

**Comment by Alex313031** [comment]
@mzinner OMFG dude! 150$!!!! That's ridiculously generous!! Thank you so much! Why would you give that much to a random small time developer like me?? For that, I will give you access to my private API Keys repo, which you can use to make your own builds of Chromium/Thorium/ChromiumOS with ulimiteted google sync quota. All I ask is please don't redistribute them.

I can get a raspberry pi 8GB now! And probably some bearings for my GPU. I took them apart and cleaned/greased them, but its been about 8 months and they are starting to sound crappy again. I think its on its way out. I'm just lucky that this card uses separate ball bearings that can be replaced separate from the fan/housing assembly.

**Comment by Alex313031** [comment]
@mzinner New raspi builds are out. M110.

**Comment by mzinner** [comment]
@Alex313031 Great, thanks! With this build I am getting the following error

```bash
mzinner@raspberrypi400:~ $ thorium-browser
find: ‘/home/mzinner/.config/thorium/Crash Reports/pending/’: No such file or directory
/usr/bin/thorium-browser: error while loading shared libraries: libminigbm.so: cannot open shared object file: No such file or directory
```

Any idea what could be causing this? Thanks!

**Comment by Alex313031** [comment]
@mzinner Are you running it on a raspberry pi with no GUI? What OS/raspi are you using?

This seems to be related to these two args > https://github.com/Alex313031/thorium/blob/ce311b3ba8e1ba32b9d9426babae0f9a1d0d77d2/arm/raspi/raspi_args.gn#L15 and https://github.com/Alex313031/thorium/blob/ce311b3ba8e1ba32b9d9426babae0f9a1d0d77d2/arm/raspi/raspi_args.gn#L16

These are specific to the raspberry pi args.gn, and tell it to use the arm64 VC4 minigbm. This allows hardware acceleration for (some) videos on raspi.

**Comment by Alex313031** [comment]
@mzinner Fixed the libminigbm.so error in the M114 release > https://github.com/Alex313031/Thorium-Special/releases/tag/M114.0.5735.134-1

**Comment by Alex313031** [comment]
@mzinner Builds for each platform now have their own repo.

Raspberry Pi builds are now located at > https://github.com/Alex313031/Thorium-Raspi

I also invited you as a collaborator there and in the new MacOS repo.

**Comment by mzinner** [comment]
It's a great idea to have separate repos for Raspberry Pi and macOS! Thanks for your great work as always!

**Comment by Alex313031** [comment]
@mzinner Here you go.

Also now includes Widevine support (I have yet to test, as my Pi 4 that you bought me is currently being used as a file server, but I will test soon)
https://github.com/Alex313031/Thorium-Raspi/releases/tag/115.0.5790.172

**Comment by Alex313031** [comment]
@mzinner M120 > https://github.com/Alex313031/Thorium-Raspi/releases/tag/M120.0.6099.235

**Comment by mzinner** [comment]
@Alex313031 thanks so much, the new build works very well. Running a quick Speedometer 2.0 test on a Raspberry Pi 5 overclocked to 2.8 GHz shows a value of 65.0 vs. the stock Chromium build value of 61.2. Please continue the good work.
