### ISSUE TITLE
Sync not working on Android

### ISSUE THREAD

**Issue by People-11** [Alex313031/Thorium-SSE3#54]
**System Details**
 - OS: Android 11
 - Thorium Version 112.0.5615.166

**Problem**
When there is a Google account already exist in the device, clicking turn on sync, it should display that account and directly next step, however, there is no account displayed on that page. And I tried to remove the account from the device, and tried to login via throium, the account logged in the device, but still not appeared in throium. 

**Screenshots**
![image](https://github.com/Alex313031/Thorium-Special/assets/41558215/33a95710-6a6d-41f9-8b51-d1e312bdd0e9)

**Additional Notes**

**Comment by gz83** [comment]
Try adding the account you want to log in to this group below, then try logging in and using the sync feature again

https://groups.google.com/u/0/a/chromium.org/g/google-browser-signin-testaccounts

@People-11

**Comment by People-11** [comment]
Joined, still, This account already exists on your device

**Comment by Alex313031** [comment]
@gz83 Since thorium uses official api keys now, adding oneself to that testaccount group is no longer necessary.

I have not tried sync on the android builds, I will test for myself.

If it still doesn't work, then I can try to debug with ADB, to get the cmdline output of thorium as it's running.

**Comment by barnir** [comment]
Noticed the same thing, it doesn't check the accounts on the phone, it just tries to add account

**Comment by carissimopaul** [comment]
I can confirm the same issue on the latest build.

**Comment by People-11** [comment]
Is there a possibility that this is a limitation of the Google Services Framework, which may not allow authorization of package names/signatures outside of the whitelist
@Alex313031

**Comment by Subhashis2007** [comment]
Once this issue is fixed, the only feature it lacks in android is extension support or advanced adblocking settings

**Comment by Alex313031** [comment]
@barnir @People-11 @carissimopaul  Yep, it is because of what @People-11 said. It is not something I can fix from my end without paying Google out the whazoo for a whitelist. However, I am still including the API Keys for Sync because without them google location services doesn't work. I will make a note on the next release linking to this issue, to let users know that it will not work.
