### ISSUE TITLE
"close-window-with-last-tab" Flag

### ISSUE THREAD

**Issue by chrisliu298** [Alex313031/Thorium-SSE3#62]
I see that some flags from Ungoogled Chromium are included in Thorium. I wonder if the flag `close-window-with-last-tab` will also be included in the future.

Thanks!

**Comment by gz83** [comment]
+Alex
@Alex313031

**Comment by Alex313031** [comment]
@chrisliu298 Doesn't Chromium already close the window when you close the last tab?

**Comment by chrisliu298** [comment]
@Alex313031 Yes that is correct. I was asking because Ungoogled Chromium gives users this flag so that they disable it to prevent closing the browser window after closing the last tab.

**Comment by Alex313031** [comment]
@chrisliu298 Ohhh I see. Let me take a look

**Comment by Alex313031** [comment]
@chrisliu298 I didn't add this, but I added the close confirmation flag, which could be used for the same purpose.
