### ISSUE TITLE
Can't open chrome://password-manager/passwords, please update it!

### ISSUE THREAD

**Issue by Sunsh4j** [Alex313031/Thorium-SSE3#66]
**System Details**
 - OS: [e.g.  Ubuntu 22.04, Windows 7, 8.1, 10, 11]
 - Thorium Version [e.g.107.0.5347.0]

**Problem**

**Screenshots**

**Additional Notes**

**Comment by Alex313031** [comment]
@Sunshagon This is because Thorium is based on Chromium 115 right now.

You should enable chrome://flags/#password-manager-redesign to use it. You are probably using a newer Chromium/Chrome if you are able to use this page without the flag enabled.

**Comment by Sunshagon** [comment]
> @Sunshagon This is because Thorium is based on Chromium 115 right now.
> 
> You should enable chrome://flags/#password-manager-redesign to use it. You are probably using a newer Chromium/Chrome if you are able to use this page without the flag enabled.

I have turned on the new ui, but when searching for a password, the results come up empty!

**Comment by gz83** [comment]
I don't know if you have any passwords saved in your browser, if you don't then of course there won't be any passwords in your password manager.

Also, don't compare the functions or features of the new version with the old version.

@Sunshagon

**Comment by Sunshagon** [comment]
> I don't know if you have any passwords saved in your browser, if you don't then of course there won't be any passwords in your password manager.
> 
> Also, don't compare the functions or features of the new version with the old version.
> 
> @Sunshagon

Yes, I saved the password. I also get a prompt when I'm on the login screen of the site. But when I search for the password, it shows up as empty, which is odd

**Comment by gz83** [comment]
> > I don't know if you have any passwords saved in your browser, if you don't then of course there won't be any passwords in your password manager.
> > Also, don't compare the functions or features of the new version with the old version.
> > @Sunshagon
> 
> Yes, I saved the password. I also get a prompt when I'm on the login screen of the site. But when I search for the password, it shows up as empty, which is odd

Turn off the experimental flags related to the password manager, can you view your saved passwords in the password manager?

@Sunshagon

**Comment by Sunshagon** [comment]
> > > I don't know if you have any passwords saved in your browser, if you don't then of course there won't be any passwords in your password manager.
> > > Also, don't compare the functions or features of the new version with the old version.
> > > @Sunshagon
> > 
> > 
> > Yes, I saved the password. I also get a prompt when I'm on the login screen of the site. But when I search for the password, it shows up as empty, which is odd
> 
> Turn off the experimental flags related to the password manager, can you view your saved passwords in the password manager?
> 
> @Sunshagon

https://github.com/Alex313031/Thorium-Special/issues/66#issuecomment-1695120862

**Comment by Sunshagon** [comment]
> > > I don't know if you have any passwords saved in your browser, if you don't then of course there won't be any passwords in your password manager.
> > > Also, don't compare the functions or features of the new version with the old version.
> > > @Sunshagon
> > 
> > 
> > Yes, I saved the password. I also get a prompt when I'm on the login screen of the site. But when I search for the password, it shows up as empty, which is odd
> 
> Turn off the experimental flags related to the password manager, can you view your saved passwords in the password manager?
> 
> @Sunshagon

As a matter of fact, after turning on the experimental flag, the password is visible in the "Check" section of the "Password Management Tool", but when searching, it is displayed as empty. In the ui after closing, the password is displayed whether or not it is searched.

**Comment by gz83** [comment]
Then it may be that the development of the new password manager in version 115 is not perfect enough. It is recommended to wait until a newer version to use the new password manager

@Sunshagon

**Comment by Sunshagon** [comment]
> Then it may be that the development of the new password manager in version 115 is not perfect enough. It is recommended to wait until a newer version to use the new password manager
> 
> @Sunshagon

Ok, thank you for your reply

**Comment by Alex313031** [comment]
@Sunsh4j The password manager has now been enabled by default since M117. The latest M119 release has it.
