### ISSUE TITLE
Sign in and sync options are non functional 

### ISSUE THREAD

**Issue by Keshav-writes-code** [Alex313031/Thorium-SSE3#68]
**System Details**
 - OS: Android 10
 - Thorium Version 117.5938.157

**Problem**
1. No way to use Sync with already signed in Gmail account. This is just bad user experience 

2. Sign in or add account is non functional.

When you want the sync and you think of signing out from your Gmail account to again sign in from thorium using "add account", after the sign in process, thorium bugs out and quits. Then after reopening thorium, you found that all that work did nothing cuz, it still isn't signed in with any account 

**Screenshots**
![Screenshot_2023-10-19-10-11-08-671_org.chromium.thorium.jpg](https://github.com/Alex313031/Thorium-SSE3/assets/95571677/7be6e95f-77da-403a-b38a-14b13eb7e3b1)

**Comment by gz83** [comment]
Not posting the issue in the correct repo, also, this issue already exists in the Thorium-Android repo
