### ISSUE TITLE
What is this repo for 

### ISSUE THREAD

**Issue by ShalokShalom** [Alex313031/Thorium-SSE3#71]
Currently, you are only telling people that this repo is for "SSE3" builds. 
What does this mean in practice?

Use case, devices?
I also hint on the fact, that you link on this repo from the README of the normal Thorium repo, with the added info, that this is for devices who lack AVX.

**Comment by gz83** [comment]
This repo is used to store the SSE3 version and some introductions to the SSE3 version. It also contains some files that we used to compile the SSE3 version, but these files are no longer used.

**Comment by ShalokShalom** [comment]
So this line is no longer up to date?

> If your CPU lacks AVX, you can use builds from [Thorium Special](https://github.com/Alex313031/Thorium-Special).

https://github.com/Alex313031/Thorium#chromium-fork-for-linux-named-after-radioactive-element-no-90-windowsmacosraspiandroidother-builds-see-below

Instead of being a less demanding build, it is a more demanding one?

**Comment by gz83** [comment]
`If your CPU lacks AVX, you can use builds from [Thorium Special](https://github.com/Alex313031/Thorium-Special).`

still valid

**Comment by ShalokShalom** [comment]
The readme of the SSE3 version does not specify anything about AVX. It just says something about SSE3 and is called "Special" in one instance and "SSE3" in another

Can you see, how this is confusing?

**Comment by gz83** [comment]
> The readme of the SSE3 version does not specify anything about AVX. It just says something about SSE3 and is called "Special" in one instance and "SSE3" in another
> 
> Can you see, how this is confusing?

Please send me the link to the file you think is in question and I will take a look

**Comment by ShalokShalom** [comment]
I already did so.

**Comment by Alex313031** [comment]
@ShalokShalom Fixed readmes in both repos.
