### ISSUE TITLE
Text gets blurry.

### ISSUE THREAD

**Issue by nikkdrive18** [Alex313031/Thorium-SSE3#72]
**System Details**
 - OS: Windows10
 - Thorium Version: 117.0.5938.157

**Problem**
Text gets blurry when moving mouse over it. Even the bookmarks and tabs get blurry.
An easy way to reproduce it is to move another program over the text( I used old Snipping Tool from accessories).
Once I  move the mouse or click on the page it goes away 
Update: Its not just text. images too.

**Screenshots**
![Thorium01](https://github.com/Alex313031/Thorium-SSE3/assets/131444909/f5c9f583-f1a6-4bc7-b2d2-9d1aad121052)
![Thorium02](https://github.com/Alex313031/Thorium-SSE3/assets/131444909/cb333eb1-6fbf-4f92-9f4e-53dfdacb65be)
![Thorium03](https://github.com/Alex313031/Thorium-SSE3/assets/131444909/ca169520-d19f-49d5-a6f7-9165101e88c5)

**Additional Notes**
This problem doesnt happen with Chrome so i dont think its my PC.
I use a 50inTV+C2D+GT610

**Comment by gz83** [comment]
Do you have experimental flags turned on in your Thorium browser?

**Comment by nikkdrive18** [comment]
I didnt change it. Its at default.

**Comment by gz83** [comment]
Completely uninstall and reinstall the browser, and also try in incognito mode to see if the issue you are experiencing still occurs.

**Comment by nikkdrive18** [comment]
Tried incognito, Uninstalled and reinstalled, then tried immediately without logging in, then tried incognito again.
same problem. Im using SSE3 - thorium_SSE3_mini_installer.
![Thorium06](https://github.com/Alex313031/Thorium-SSE3/assets/131444909/e7fc03e3-b52c-415a-8c36-a12cd0276562)
![Thorium07](https://github.com/Alex313031/Thorium-SSE3/assets/131444909/3e77e050-a852-454a-8c15-33d373855091)
![Thorium08](https://github.com/Alex313031/Thorium-SSE3/assets/131444909/b8f538ef-29ca-4ec8-a49a-4693c9815ec4)

**Comment by nikkdrive18** [comment]
The text was blurry even after reinstalling. But today somehow its working correctly without me doing anything to fix it, so im going to close this issue. If the problem returns ill post an update.
![Thorium09](https://github.com/Alex313031/Thorium-SSE3/assets/131444909/ed402fdb-aaf4-4b2e-a16e-4ef67fa77dcf)
